GSOC final pull request
dbpedia/extraction-framework pull request #740
Opened 2022-09-14 16:41 UTC by datalogism

Pushing all the work made during the GSOC

2022-09-14 17:10 UTC, TallTed commented on core/src/main/scala/org/dbpedia/extraction/util/MediawikiConnectorConfigured.scala
> +    // Implemented but usefull ?
```suggestion
    // Implemented but useful?
```

2022-09-14 17:19 UTC, TallTed commented on dump/src/test/scala/org/dbpedia/extraction/dump/ExtractionTestAbstract.md
> +* rebuild the app with ``` mvn install ``` or just test it with ```  mvn test -Dtest="ExtractionTestAbstract2" ```
```suggestion
1. Clean your target directory with `mvn clean` in the root directory of DIEF
1. Go to bash scripts via `cd /dump/src/test/bash`
1. OPTIONAL: Create a new Wikipedia minidump sample with `bash create_custom_sample.sh -n $numberOfPage -l $lang -d $optionalDate`
1. Process sample of Wikipedia pages `bash Minidump_custom_sample.sh -f $filename/lst`
1. Update the extraction language parameter for your minidump sample in [`extraction.nif.abstracts.properties`](https://github.com/datalogism/extraction-framework/blob/gsoc-celian/dump/src/test/resources/extraction-configs/extraction.nif.abstracts.properties) and in [`extraction.plain.abstracts.properties`](https://github.com/datalogism/extraction-framework/blob/gsoc-celian/dump/src/test/resources/extraction-configs/extraction.plain.abstracts.properties)
1. Change the name of your log in the [`ExtractionTestAbstract.scala`](https://github.com/datalogism/extraction-framework/blob/gsoc-celian/dump/src/test/scala/org/dbpedia/extraction/dump/ExtractionTestAbstract.scala) file
1. Rebuild the app with `mvn install`, or just test it with `mvn test -Dtest="ExtractionTestAbstract2"`
```

2022-09-14 17:20 UTC, TallTed commented on dump/src/test/scala/org/dbpedia/extraction/dump/ExtractionTestAbstract.scala
> +          if(failed.toString().contains("Server returned HTTP response code: 429")){
```suggestion
          if (failed.toString().contains("Server returned HTTP response code: 429")){
```

2022-09-14 17:21 UTC, TallTed requested changes
Reviewed commit by commit....

2022-09-14 17:22 UTC, TallTed commented on dump/src/test/scala/org/dbpedia/extraction/dump/ExtractionTestAbstract.scala
> +      mapLocal += "numberOfFailedPagesOutOfMemoryError" ->numberOfFailedPagesOutOfMemoryError.toString
for code style consistency with neighboring lines
```suggestion
      mapLocal += "numberOfFailedPagesOutOfMemoryError" -> numberOfFailedPagesOutOfMemoryError.toString
```

2022-09-14 17:23 UTC, TallTed commented on core/src/main/scala/org/dbpedia/extraction/config/Config.scala
>      case Failure(f) => throw new IllegalArgumentException("Not all necessary parameters for the 'MediaWikiConnection' class were provided or could not be parsed to the expected type.", f)
```suggestion
    case Failure(f) => throw new IllegalArgumentException("Some parameters necessary for the 'MediaWikiConnection' class were not provided or could not be parsed to the expected type.", f)
```

2022-09-14 17:24 UTC, TallTed commented on core/src/main/scala/org/dbpedia/extraction/config/Config.scala
>      * Number of parallel processes allowed. Depends on the number of cores, type of disk and IO speed
```suggestion
    * Number of parallel processes allowed. Depends on the number of cores, type of disk, and IO speed
```

2022-09-16 16:04 UTC, datalogism commented
> @celian_ringwald @datalogism — Are these all intermingled and/or interdependent? If not, it seems to me that each GSOC work item should have its own PR, rather than all being mushed into one. This will make all of them easier to review, among other things. (I recognize that it would be more work on your part, but I do think it would be worthwhile.)

Sorry @TallTed  I had no instructions about this, this is my first main pull request :s

2022-09-16 23:29 UTC, TallTed approved these changes

2022-09-18 10:57 UTC, jlareck requested changes

2022-09-18 10:57 UTC, jlareck commented on core/src/main/scala/org/dbpedia/extraction/util/MediawikiConnectorConfigured.scala
> +        if (retryAfter && answer_clean.contains("retry-after") ){
change variable names from snake case to camel case

2022-09-18 10:57 UTC, jlareck commented on core/src/main/scala/org/dbpedia/extraction/util/MediawikiConnectorConfigured.scala
> +        println(s"mediawikiurl: $apiUrl?$parameters")
comment all printlns that you added

2022-09-22 07:37 UTC, merged