[GSOC'24 Amharic chapter] Extend Existing Extractors For Amharic
dbpedia/extraction-framework pull request #766
Opened 2024-08-21 17:40 UTC by Meti-Adane

- Added Amharic configurations to extend existing extractors 
- Added associated tests
- Included extended extractors in property files

2024-08-22 17:47 UTC, TallTed requested changes
Human facing. Small stuff.

2024-08-22 17:47 UTC, TallTed commented on core/src/main/scala/org/dbpedia/extraction/config/dataparser/ParserUtilsConfig.scala
>          // Don't change this else if you know how it is done.
```suggestion
        // Don't change this unless you know how it works.
```

2024-08-22 17:47 UTC, TallTed commented on core/src/main/scala/org/dbpedia/extraction/config/mappings/DateIntervalMappingConfig.scala
>      // Don't change this else if you know how it is done.
```suggestion
    // Don't change this unless you know how it works.
```

2024-09-02 09:48 UTC, jimkont approved these changes
looks great, we should also incorporate @TallTed 's documentation suggestions

2024-12-11 13:53 UTC, merged